
# Site settings
title: Sparkling Data Ocean
header-img: img/home_sdo2f.jpg
email: sparkling.dataocean@gmail.com
copyright_name: Graph AI Studio
description: "Spark for Big Data Analytics."

url: "http://sparklingdataocean.com/"

email_username:  sparkling.dataocean@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: "UA-114694347-1"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed]
